# Generated by Django 5.1.7 on 2025-03-15 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_reference_no", models.CharField(max_length=255, unique=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_COLLECTION", "In Collection"),
                            ("PAID_IN_FULL", "Paid in Full"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="IN_COLLECTION",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="accounts.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_info", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Collection Agencies",
                "indexes": [
                    models.Index(fields=["name"], name="accounts_co_name_174dbb_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="collection_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="accounts.collectionagency",
            ),
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("ssn", models.CharField(max_length=11)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="accounts_co_name_461d0c_idx"),
                    models.Index(fields=["ssn"], name="accounts_co_ssn_54d65f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountConsumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.consumer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="consumers",
            field=models.ManyToManyField(
                related_name="accounts",
                through="accounts.AccountConsumer",
                to="accounts.consumer",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="accounts_cl_name_024fa1_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["collection_agency"], name="accounts_cl_collect_0d237d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountconsumer",
            index=models.Index(
                fields=["account"], name="accounts_ac_account_e01485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountconsumer",
            index=models.Index(
                fields=["consumer"], name="accounts_ac_consume_f9c581_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountconsumer",
            unique_together={("account", "consumer")},
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["client_reference_no"], name="accounts_ac_client__eef771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["balance"], name="accounts_ac_balance_3b70f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["status"], name="accounts_ac_status_07de41_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["client"], name="accounts_ac_client__1d73d3_idx"
            ),
        ),
    ]
